name: Deploy .NET Lambda Function

on:
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Build and Package Lambda
      run: |
        dotnet tool restore
        dotnet restore
        dotnet build --configuration Release
        cd src/lyrics-game-lambda
        dotnet lambda package

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        cd src/lyrics-game-lambda
        dotnet lambda deploy-function lyrics-game-lambda --function-role "arn:aws:iam::915898657279:role/service-role/lyrics-game-lambda-role-5enu4vjm" --region ${{ secrets.AWS_REGION }}
  
